/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package delme;

import java.util.ArrayList;
import java.util.List;

public class Merge {
    private Merge() {
    }
    
    public static <E extends Comparable<E>> List<E> merge(List<E> left, List<E> right) {
        List<E> output = new ArrayList<>();
        int li = 0;
        int ri = 0;
        E currentRight = right.get(ri);
        while (li < left.size()) {
            E currentLeft = left.get(li);
            if (currentLeft.compareTo(currentRight) > 0) {
                int ti = li;
                li = ri;
                ri = ti;
                var temp = left;
                left = right;
                right = temp;
                currentRight = currentLeft;
                continue;
            }
            output.add(currentLeft);
            li++;
        }
        output.addAll(right.subList(ri, right.size()));
        return output;
    }
}
